### ISSUE TITLE
Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'hedgedoc'@'hedgedoc.hedgedoc_default' (using password: YES)

### ISSUE THREAD

**Issue by NigelBoxing** [linuxserver/docker-hedgedoc#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

The docker container 'hedgedoc' can't run correctly.

## Steps to Reproduce

```yaml
version: '3'
services:
  database:
      image: ghcr.io/linuxserver/mariadb
      container_name: hedgedoc_db
      environment:
        - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/dbrootpassword
        - MYSQL_USER=hedgedoc
        - FILE__MYSQL_PASSWORD=/run/secrets/dbpassword
        - MYSQL_DATABASE=hedgedoc
        # - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - PGID=1000
        - PUID=1000
        - TZ=Europe/London
      volumes:
        - database:/config
      restart: always
      # secret names in this service
      secrets:
        - dbpassword
        - dbrootpassword

  hedgedoc:
    image: ghcr.io/linuxserver/hedgedoc
    container_name: hedgedoc
    environment:
      - DB_HOST=database
      - DB_USER=hedgedoc
      - FILE__DB_PASS=/run/secrets/dbpassword
      - DB_NAME=hedgedoc
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - uploads:/config
    ports:
      - "88:3000"
    restart: always
    depends_on:
      - database
    # secret names in this service
    secrets:
      - dbpassword

volumes:
  database:
  uploads:

secrets:
  # source of all docker secrets
  dbpassword:
    file: ./dbpassword.txt
  dbrootpassword:
    file: dbrootpassword.txt
```
1. docker-compose up -d
2. docker logs -f hedgedoc

## Environment
**OS:** CentOS 7.9
**CPU architecture:** x86_64
**How docker service was installed:** 3

## Docker logs

```bash
2021-08-16T15:51:28.137Z warn:  Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2021-08-16T15:51:28.143Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'hedgedoc'@'hedgedoc.hedgedoc_default' (using password: YES)
    at /opt/hedgedoc/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19
    at tryCatcher (/opt/hedgedoc/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/hedgedoc/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/hedgedoc/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/hedgedoc/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/hedgedoc/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/opt/hedgedoc/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/hedgedoc/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/hedgedoc/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/hedgedoc/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by TheSpad** [comment]
This isn't a Hedgedoc issue, it's an issue with supplying the correct crednetials to the containers.

For a start you're not consistently references the secrets
```yaml
secrets:
  # source of all docker secrets
  dbpassword:
    file: ./dbpassword.txt
  dbrootpassword:
    file: dbrootpassword.txt
```
Beyond that you need to ensure that the envs are being set inside the containers with the strings you are expecting. i.e. `docker exec database printenv MYSQL_ROOT_PASSWORD`.
