### ISSUE TITLE
Table 'hedgedoc.notes' doesn't exist in engine

### ISSUE THREAD

**Issue by JJGO** [linuxserver/docker-hedgedoc#7]
Docker compose fails with the current image and `docker-compose.yml`. There seems to be an issue with the `notes` table in the DB backend.

I did not do any modifications to the docker-compose besides changing the password and specifying the paths to the bind mounts.

## Environment
**OS:** macOS 10.15.7
**CPU architecture:** x86_64
**How docker service was installed:** Docker Desktop App for mac

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up`

## Docker logs

```
❯ docker-compose up
Creating hedgedoc_mariadb ... done
Creating hedgedoc         ... done
Attaching to hedgedoc_mariadb, hedgedoc
mariadb_1   | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
mariadb_1   | [s6-init] ensuring user provided files have correct perms...exited 0.
mariadb_1   | [fix-attrs.d] applying ownership & permissions fixes...
mariadb_1   | [fix-attrs.d] done.
mariadb_1   | [cont-init.d] executing container initialization scripts...
mariadb_1   | [cont-init.d] 01-envfile: executing... 
mariadb_1   | [cont-init.d] 01-envfile: exited 0.
mariadb_1   | [cont-init.d] 10-adduser: executing... 
mariadb_1   | 
mariadb_1   | -------------------------------------
mariadb_1   |           _         ()
mariadb_1   |          | |  ___   _    __
mariadb_1   |          | | / __| | |  /  \ 
mariadb_1   |          | | \__ \ | | | () |
mariadb_1   |          |_| |___/ |_|  \__/
mariadb_1   | 
mariadb_1   | 
mariadb_1   | Brought to you by linuxserver.io
mariadb_1   | -------------------------------------
mariadb_1   | 
mariadb_1   | To support LSIO projects visit:
mariadb_1   | https://www.linuxserver.io/donate/
mariadb_1   | -------------------------------------
mariadb_1   | GID/UID
mariadb_1   | -------------------------------------
mariadb_1   | 
mariadb_1   | User uid:    1000
mariadb_1   | User gid:    1000
mariadb_1   | -------------------------------------
mariadb_1   | 
mariadb_1   | [cont-init.d] 10-adduser: exited 0.
mariadb_1   | [cont-init.d] 30-config: executing... 
mariadb_1   | [cont-init.d] 30-config: exited 0.
mariadb_1   | [cont-init.d] 40-initialise-db: executing... 
mariadb_1   | Setting Up Initial Databases
mariadb_1   | Installing MariaDB/MySQL system tables in '/config/databases' ...
hedgedoc    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
hedgedoc    | [s6-init] ensuring user provided files have correct perms...exited 0.
hedgedoc    | [fix-attrs.d] applying ownership & permissions fixes...
hedgedoc    | [fix-attrs.d] done.
hedgedoc    | [cont-init.d] executing container initialization scripts...
hedgedoc    | [cont-init.d] 01-envfile: executing... 
hedgedoc    | [cont-init.d] 01-envfile: exited 0.
hedgedoc    | [cont-init.d] 10-adduser: executing... 
hedgedoc    | 
hedgedoc    | -------------------------------------
hedgedoc    |           _         ()
hedgedoc    |          | |  ___   _    __
hedgedoc    |          | | / __| | |  /  \ 
hedgedoc    |          | | \__ \ | | | () |
hedgedoc    |          |_| |___/ |_|  \__/
hedgedoc    | 
hedgedoc    | 
hedgedoc    | Brought to you by linuxserver.io
hedgedoc    | -------------------------------------
hedgedoc    | 
hedgedoc    | To support LSIO projects visit:
hedgedoc    | https://www.linuxserver.io/donate/
hedgedoc    | -------------------------------------
hedgedoc    | GID/UID
hedgedoc    | -------------------------------------
hedgedoc    | 
hedgedoc    | User uid:    1000
hedgedoc    | User gid:    1000
hedgedoc    | -------------------------------------
hedgedoc    | 
hedgedoc    | [cont-init.d] 10-adduser: exited 0.
hedgedoc    | [cont-init.d] 30-config: executing... 
mariadb_1   | 2021-01-26 17:56:47 6 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
hedgedoc    | Waiting for Mysql service
hedgedoc    | Waiting for Mysql service
hedgedoc    | Waiting for Mysql service
mariadb_1   | OK
mariadb_1   | 
mariadb_1   | To start mysqld at boot time you have to copy
mariadb_1   | support-files/mysql.server to the right place for your system
mariadb_1   | 
mariadb_1   | 
mariadb_1   | Two all-privilege accounts were created.
mariadb_1   | One is root@localhost, it has no password, but you need to
mariadb_1   | be system 'root' user to connect. Use, for example, sudo mysql
mariadb_1   | The second is abc@localhost, it has no password either, but
mariadb_1   | you need to be the system 'abc' user to connect.
mariadb_1   | After connecting you can set the password, if you would need to be
mariadb_1   | able to connect as any of these users with a password and without sudo
mariadb_1   | 
mariadb_1   | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
mariadb_1   | MySQL manual for more instructions.
mariadb_1   | 
mariadb_1   | You can start the MariaDB daemon with:
mariadb_1   | cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'
mariadb_1   | 
mariadb_1   | You can test the MariaDB daemon with mysql-test-run.pl
mariadb_1   | cd '/usr/mysql-test' ; perl mysql-test-run.pl
mariadb_1   | 
mariadb_1   | Please report any problems at http://mariadb.org/jira
mariadb_1   | 
mariadb_1   | The latest information about MariaDB is available at http://mariadb.org/.
mariadb_1   | You can find additional information about the MySQL part at:
mariadb_1   | http://dev.mysql.com
mariadb_1   | Consider joining MariaDB's strong and vibrant community:
mariadb_1   | https://mariadb.org/get-involved/
mariadb_1   | 
mariadb_1   | 2021-01-26 17:56:52 0 [Note] mysqld (mysqld 10.4.17-MariaDB-1:10.4.17+maria~bionic-log) starting as process 332 ...
mariadb_1   | 2021-01-26 17:56:52 0 [Warning] Setting lower_case_table_names=2 because file system for /config/databases/ is case insensitive
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Using Linux native AIO
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Uses event mutexes
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Number of pools: 1
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1   | 2021-01-26 17:56:52 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Waiting for purge to start
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: 10.4.17 started; log sequence number 60967; transaction id 20
mariadb_1   | 2021-01-26 17:56:52 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Loading buffer pool(s) from /config/databases/ib_buffer_pool
mariadb_1   | 2021-01-26 17:56:52 0 [Note] InnoDB: Buffer pool(s) load completed at 210126 17:56:52
mariadb_1   | 2021-01-26 17:56:52 0 [Note] Server socket created on IP: '::'.
mariadb_1   | 2021-01-26 17:56:52 0 [Note] Reading of all Master_info entries succeeded
mariadb_1   | 2021-01-26 17:56:52 0 [Note] Added new Master_info '' to hash table
mariadb_1   | 2021-01-26 17:56:52 0 [Note] mysqld: ready for connections.
mariadb_1   | Version: '10.4.17-MariaDB-1:10.4.17+maria~bionic-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1   | 2021-01-26 17:56:54 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
mariadb_1   | 2021-01-26 17:56:54 0 [Note] Event Scheduler: Purging the queue. 0 events
mariadb_1   | 2021-01-26 17:56:54 11 [Warning] Aborted connection 11 to db: 'unconnected' user: 'unauthenticated' host: 'hedgedoc.hedgedoc_default' (This connection closed normally without authentication)
mariadb_1   | 2021-01-26 17:56:54 0 [Note] InnoDB: FTS optimize thread exiting.
mariadb_1   | 2021-01-26 17:56:54 0 [Note] InnoDB: Starting shutdown...
mariadb_1   | 2021-01-26 17:56:54 0 [Note] InnoDB: Dumping buffer pool(s) to /config/databases/ib_buffer_pool
mariadb_1   | 2021-01-26 17:56:54 0 [Note] InnoDB: Buffer pool(s) dump completed at 210126 17:56:54
mariadb_1   | 2021-01-26 17:56:55 0 [Note] InnoDB: Shutdown completed; log sequence number 60976; transaction id 23
mariadb_1   | 2021-01-26 17:56:55 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mariadb_1   | 2021-01-26 17:56:55 0 [Note] mysqld: Shutdown complete
mariadb_1   | 
mariadb_1   | Database Setup Completed
mariadb_1   | [cont-init.d] 40-initialise-db: exited 0.
mariadb_1   | [cont-init.d] 99-custom-scripts: executing... 
mariadb_1   | [custom-init] no custom files found exiting...
mariadb_1   | [cont-init.d] 99-custom-scripts: exited 0.
mariadb_1   | [cont-init.d] done.
mariadb_1   | [services.d] starting services
mariadb_1   | [services.d] done.
mariadb_1   | 210126 17:56:57 mysqld_safe Logging to syslog.
mariadb_1   | 210126 17:56:57 mysqld_safe Starting mysqld daemon with databases from /config/databases
hedgedoc    | [cont-init.d] 30-config: exited 0.
hedgedoc    | [cont-init.d] 99-custom-scripts: executing... 
hedgedoc    | [custom-init] no custom files found exiting...
hedgedoc    | [cont-init.d] 99-custom-scripts: exited 0.
hedgedoc    | [cont-init.d] done.
hedgedoc    | [services.d] starting services
hedgedoc    | [services.d] done.
hedgedoc    | 
hedgedoc    | Sequelize CLI [Node: 12.20.1, CLI: 5.5.1, ORM: 5.22.3]
hedgedoc    | 
hedgedoc    | Loaded configuration file "../../config/config.json".
hedgedoc    | == 20150504155329-create-users: migrating =======
hedgedoc    | == 20150504155329-create-users: migrated (0.070s)
hedgedoc    | 
hedgedoc    | == 20150508114741-create-notes: migrating =======
hedgedoc    | == 20150508114741-create-notes: migrated (0.034s)
hedgedoc    | 
hedgedoc    | == 20150515125813-create-temp: migrating =======
hedgedoc    | == 20150515125813-create-temp: migrated (0.030s)
hedgedoc    | 
hedgedoc    | == 20150702001020-update-to-0_3_1: migrating =======
hedgedoc    | 
hedgedoc    | 
hedgedoc    | ERROR: Table 'notes' is marked as crashed and should be repaired
hedgedoc    | 
hedgedoc    | Sequelize CLI [Node: 12.20.1, CLI: 5.5.1, ORM: 5.22.3]
hedgedoc    | 
hedgedoc    | Loaded configuration file "../../config/config.json".
hedgedoc    | == 20150702001020-update-to-0_3_1: migrating =======
hedgedoc    | 
hedgedoc    | 
hedgedoc    | ERROR: Table 'hedgedoc.notes' doesn't exist in engine
hedgedoc    | 
hedgedoc    | Sequelize CLI [Node: 12.20.1, CLI: 5.5.1, ORM: 5.22.3]
hedgedoc    | 
hedgedoc    | Loaded configuration file "../../config/config.json".
hedgedoc    | == 20150702001020-update-to-0_3_1: migrating =======
hedgedoc    | 
hedgedoc    | ERROR: Table 'hedgedoc.notes' doesn't exist in engine
hedgedoc    | 
hedgedoc    | 
hedgedoc    | Sequelize CLI [Node: 12.20.1, CLI: 5.5.1, ORM: 5.22.3]
hedgedoc    | 
hedgedoc    | Loaded configuration file "../../config/config.json".
hedgedoc    | == 20150702001020-update-to-0_3_1: migrating =======
hedgedoc    | 
...
```

**Comment by JJGO** [comment]
Why has the issue been tagged as invalid?

1. I copied the `docker-compose.yml` from the `README.md`
2. I change the `/path/to` with `.` and changed the password
3. Last, I ran `docker-compose up` and got the errors.

Please let me know if there's anything I can help with, I'm not sure what I'm doing wrong

**Comment by tobbenb** [comment]
Because you didn't supply all the info we ask for. Saying that you just used the compose from the readme is not good enough.

**Comment by JJGO** [comment]
Ok. I'm not sure what else you need since you don't ask for more details.

I couldn't find any installation instructions and most other LS services do not require any other setup beyond the docker compose.

Here's the `docker-compose.yml`

```yaml
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: hedgedoc_mariadb
    restart: always
    volumes:
      - ./data:/config
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=password
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  hedgedoc:
    image: ghcr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=hedgedoc
      - DB_PASS=password
      - DB_NAME=hedgedoc
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
```

I start it with `docker-compose up` and get the logs I included when opening the issue that seem to suggest something is wrong with table `hedge.notes`. 

Env details:

- OS: macOS 10.15.7
- Docker version 20.10.2, build 2291f61
- docker-compose version 1.27.4, build 40524192

Happy to provide more info, but I'm really not sure what else to include without pointers.

**Comment by tobbenb** [comment]
We have the issue template for a reason. You did not post what we asked for in the template, hence the invalid label. Do we need to ask you twice before you supply info?

If you would have posted the compose when you opened the issue, we would have found the issue straight away. Instead we have to waste time asking you to supply the info we ask for already. 

You have set the dB host to mariadb, but you call the mariadb container hedgedoc_mariadb. You have to call it either mariadb or change the dB host variable to hedgedoc_mariadb. You don't really need separate mariadb containers for every container that needs a database. You can create multiple databases in the same mariadb container.

Closing this as it's not a bug. Issues should be addressed in our discourse forum or our discord server.

**Comment by JJGO** [comment]
Your comments and preemptively closing the issue without checking that it was solved do come off as quite hostile which deters newer users from contributing. 

The DNS resolution works both with `hostname` and `container_name` ([1](https://stackoverflow.com/questions/55522620/docker-compose-yml-container-name-and-hostname)) and my logs showed that connection to the DB could be established, so that is clearly not the issue.

I was able to get the same `docker-compose.yml` working in a Linux box so the issue somehow seems to be platform dependent.

I'd reopen the issue, but I can't, so I guess I'll use the `hedgedoc/container` image since that works on macOS Docker.

Lastly, I appreciate you have other platforms of communication such as Discourse/Discord, but I do believe GitHub issues is the correct form of communication for keeping track of *issues* with your repo. They are very useful as reference for future users facing similar problems.

**Comment by Roxedus** [comment]
It's not a issue, I cannot reproduce, using a carbon-copy of your compose. I did let mariadb start up properly in my test however, even though hedgedoc container should account for that.

It very well be a nuance with docker for mac.

**Comment by aptalca** [comment]
`ERROR: Table 'notes' is marked as crashed and should be repaired`

This is the main issue. It could be a one time glitch, it it could be db corruption due to filesystem used.

Afaik, docker on mac runs in a vm, so the config folder you're mapping may be on some type of fuse system that is shared between the host and the docker vm, and that may lead to db corruption.

**Comment by JJGO** [comment]
Ok, that makes sense, thanks for the feedback. I don't think it's a one time glitch since I got the issue at least three times (in between retries I made sure to delete the host mounts, containers and images to ensure a fresh install). 

I might try using a volume instead of a bind mount and see whether that helps. In the meantime I managed to get it working using Postgres instead with the following `docker-compose.yml`. Thus, I think the issue is with the `mariadb` docker image and not hedgedoc one and should be moved there. 

```yml
version: '3'    
                       
services:                   
  database:                
    image: postgres:latest
    container_name: hedgedoc_db
    restart: unless-stopped
    volumes:    
      - ./data:/var/lib/postgresql/data                            
    environment:                    
      - POSTGRES_USER=hedgedoc                                             
      - POSTGRES_DB=hedgedoc
      - POSTGRES_PASSWORD=password                                         
  hedgedoc:                
    image: ghcr.io/linuxserver/hedgedoc:latest                                 
    container_name: hedgedoc
    restart: unless-stopped                                                                                                                              
    depends_on:                                                                
      - database                                                               
    volumes:                                                                   
      - ./config:/config                                           
    environment:                                                               
      - CMD_DB_URL=postgres://hedgedoc:password@hedgedoc_db:5432/hedgedoc      
      - TZ=America/New_York                                                    
      - PGID=1000                                                    
      - PUID=1000                                                          
```
